apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-servicemesh-operator-singapore-cluster
  annotations:
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-istio-system
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: istio-system
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-servicemesh-operator
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: servicemeshoperator
                  namespace: openshift-operators
                spec:
                  channel: stable
                  name: servicemeshoperator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-jaeger-product
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: jaeger-product
                  namespace: openshift-operators
                spec:
                  channel: stable
                  name: jaeger-product
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-kiali-ossm
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: kiali-ossm
                  namespace: openshift-operators
                spec:
                  channel: stable
                  name: kiali-ossm
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-service-mesh-control-plane
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: maistra.io/v2
                kind: ServiceMeshControlPlane
                metadata:
                  namespace: istio-system
                  name: basic
                spec:
                  addons:
                    grafana:
                      enabled: true
                    jaeger:
                      install:
                        storage:
                          type: Memory
                    kiali:
                      enabled: true
                    prometheus:
                      enabled: true
                  policy:
                    type: Istiod
                  telemetry:
                    type: Istiod
                  tracing:
                    sampling: 10000
                    type: Jaeger
          severity: low
          remediationAction: enforce
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-service-mesh-member-roll
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: maistra.io/v1
                kind: ServiceMeshMemberRoll
                metadata:
                  name: default
                  namespace: istio-system
                spec:
                  members:
                  # a list of namespaces that should be joined into the service mesh
                  # for example, to add the bookinfo namespace
                  - bookinfo
                  - bank-infra
                  - travel-agency
                  - travel-portal
                  - travel-control
          severity: low
          remediationAction: enforce
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-servicemesh-operator-singapore-cluster
placementRef:
  name: placement-policy-servicemesh-operator-singapore-cluster
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-servicemesh-operator-singapore-cluster
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-servicemesh-operator-singapore-cluster
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["singapore-cluster"]}
